Plot predictions along with inputs and outputs (#23)
* Read predictions from `DatasetGenerator`

* Plot predictions along with inputs and outputs

* Defer to `dataset` for plotting predictions

* Remove error messages due to GUI backend

The error message was:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 4014, in 
__del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
```
Resolve as per https://stackoverflow.com/a/51178529/8376138.

* Support `phase` in animations and plots

* Fix order of predictions' path

* Account for `inputs` not being in predictions

* Use `h5.File` with `with`

* Use `TkAgg` instead of `Agg`

Remove the error message from prior to 14cbed476, but also show the 
figures, as per https://stackoverflow.com/a/55309207/8376138.

* Add docstring to `read_predictions`

* Revert 1679a18 and 14cbed476

The error message still shows up.

* Add a row of subplots to account for predictions

* Fix testing batch size

* Renamed architecture in main.py to nn

* Rename `architecture` to `nn` in `AutomatedTraining`

* Store the predictions in architecture-specific folders

* Have `DatasetGenerator` save the predictions

* Use `with` in `DatasetGenerator.write`

* Remove unused imports

* Add a `naxes` attribute to inputs and outputs

* Enhance documentation

* Use an iterative, more general logic in plotting

* Span the same quantity of columns for each plot row

* Default to the clipped absolute maximum in plots

Use absolute maximum instead of bar maximum in finding the default clip 
values of plots.

* Allow IOs' plots to return multiple images

* Allow `is_1d` and `naxes` to change dynamically

Subclassing datasets and replacing `dataset.acquire.single_shot` 
prevented the

* Plot a zero-offset gather when using 2D data

* Added the nmin argument to MarineModel to work with the new version of ModelGenerator

* Constant offset plotting is fixed

* Update requirement for `ModelGenerator`

Account for d4ad87d.

* ModelGenerator v0.1.1 now required

Co-authored-by: Gabriel Fabien-Ouellet <gabriel.fabien-ouellet@polymtl.ca>