Remove `__init__.py` files and flat imports
Having flat imports caused circular imports. For instance, Python could 
not import `GeoDataset` due to relying on importing `DatasetGenerator` 
from `GeoFlow`. Here is the traceback of the error:
```
File "main.py", line 5, in <module>
    from GeoFlow.Trainer import Trainer
  File "Deep_2D_velocity/GeoFlow/__init__.py", line 1, in <module>
    from .GeoDataset import GeoDataset
  File "Deep_2D_velocity/GeoFlow/GeoDataset.py", line 20, in <module>
    from GeoFlow import DatasetGenerator
  File "Deep_2D_velocity/GeoFlow/DatasetGenerator.py", line 15, in 
<module>
    from GeoFlow import SeismicGenerator, Acquisition
ImportError: cannot import name 'Acquisition' from partially initialized 
module 'GeoFlow' (most likely due to a circular import) 
(Deep_2D_velocity/GeoFlow/__init__.py)
```