Remove error messages due to GUI backend
The error message was:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 4014, in 
__del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
```
Resolve as per https://stackoverflow.com/a/51178529/8376138.